

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
      
spring:  application:    name: greetings-service
    
server:  port: 8002
  
security:  oauth2:    resource:
      id: ${spring.application.name}
      service-id: ${spring.application.name}      jwt:        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoKaBnS8z2C+BTO0UVV2zbaUSPQYQZyMfwxwwwe8+QuRTnVG0IqBPD9CaJH7zAzVaThJIM3l3L9zqKsK50F13hO0/vbAUmAESHu2DOGwrrv7hUhGs6UI9s02ZMQcynCrcYhbo3N/NdQW4Z3iMywkNijsDP23P98eB9hwTg9FRL2Gvgj69IHmggG0DJ+q5SPl8yWhjoe1IO9H2ebH3+MUvPTTv+YRVo3WUE2/XuJTea0OtAs+K35pb6sp4NXpr8O4PdhkOeW98A/gz+asqnOUVHgnTsiIvOuwXerP10vD6zk7WtQEGQOllbe/ORKSze7ceU68T+K7V5NL3YpsUgOaelwIDAQAB
            -----END PUBLIC KEY-----