server:  port: 8000
  use-forward-headers: true
  
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
      
      
zuul:
  add-host-header: true
  ignored-services: "*"  include-debug-header: true  routes:
    oauth2-service:
      service-id: oauth2-service
      path: /uaa/**
      strip-prefix: false      sensitive-headers:      
    ui-service:
      service-id: ui-service
      path: /ui/**
      strip-prefix: false      sensitive-headers:logging:  level:    com.example.demo.filter: NONE    org.springframework.cloud.netflix.zuul.filters: DEBUG