eureka:
  client:
    fetch-registry: false    register-with-eureka: false#    service-url:#      defaultZone: http://localhost:8761/eureka/,http://192.168.0.18:8761/eureka/

server:  port: 8761
  
spring:  application:    name: eureka-service